env:
  global:
    - CC_TEST_REPORTER_ID=a30a6b74efd89e74f691a51119b224b56ac52afd9a82de4d7c3ca5e1940bd954
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python -m spacy download en
script:
  - cd RohBot
  - python -m pytest --cov=./
  - codecov

